import { Process } from './process';

export const ProcessMock: Process[] = [
  new Process (
    1,
     'Prozess1',
     'Dresden',
     'Prof. Freitag',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
    ),
  new Process(
    2,
    'Prozess2',
    'Leipzig',
    'Prof. Sonntag',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
  ),
  new Process(
    3,
    'Prozess3',
    'Chemnitz',
    'Prof. Montag',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
  ),
  new Process(
    4,
    'Prozess4',
    'Freiberg',
    'Prof. Mittwoch',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
  ),
  new Process(
    5,
    'Prozess5',
    'Flöha',
    'Prof. Donnerstag',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
  ),
  new Process(
    9,
    'Prozess6',
    'Dresden',
    'Prof. Freitag',
      'Stadt Dresden',
      'Dieser Prozess finden in aller Öffentlichkeit statt.',
      'Prozess 0',
  ),
];
